# AI_MEMORY setup
# Windows PowerShell 5.1 compatible and ASCII-only by design.

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path $PSScriptRoot).Path
$SkillsRoot = Join-Path $RepoRoot "skills"
$RulesRoot = Join-Path $RepoRoot "rules"
$RulesAggregatorPath = Join-Path $RulesRoot "RULES.md"
$GlobalInstructionSource = Join-Path $RepoRoot "instructions\GLOBAL_AGENT_INSTRUCTIONS.md"
$CursorPluginRoot = Join-Path $RepoRoot "adapters\cursor-plugin"
$CursorPluginManifest = Join-Path $CursorPluginRoot ".cursor-plugin\plugin.json"
$CursorPluginRulesRoot = Join-Path $CursorPluginRoot "rules"
$ManagedStart = "<!-- AI_MEMORY_MANAGED_START -->"
$ManagedEnd = "<!-- AI_MEMORY_MANAGED_END -->"

$RuleDefinitions = @(
    [pscustomobject]@{ Source = "db-safety.md"; Adapter = "db-safety.mdc"; Description = "AI_MEMORY database access and credential safety rules." },
    [pscustomobject]@{ Source = "git-safety.md"; Adapter = "git-safety.mdc"; Description = "AI_MEMORY Git safety rules." },
    [pscustomobject]@{ Source = "engineering-principles.md"; Adapter = "engineering-principles.mdc"; Description = "AI_MEMORY shared engineering principles." }
)

function Normalize-Text {
    param([AllowEmptyString()][string]$Text = "")
    if ($null -eq $Text) { return "" }
    return (($Text -replace "`r`n", "`n" -replace "`r", "`n").Trim())
}

function Normalize-ComparablePath {
    param([Parameter(Mandatory = $true)][string]$Path)
    return $Path.TrimEnd([char[]]"\/")
}

function Get-ResolvedPathOrNull {
    param([Parameter(Mandatory = $true)][string]$Path)
    try { return (Resolve-Path $Path -ErrorAction Stop).Path }
    catch { return $null }
}

function Test-SamePath {
    param(
        [Parameter(Mandatory = $true)][string]$PathA,
        [Parameter(Mandatory = $true)][string]$PathB
    )

    $a = Get-ResolvedPathOrNull -Path $PathA
    $b = Get-ResolvedPathOrNull -Path $PathB
    if ($null -eq $a -or $null -eq $b) { return $false }
    return (Normalize-ComparablePath $a) -ieq (Normalize-ComparablePath $b)
}

function Test-CommandExists {
    param([Parameter(Mandatory = $true)][string]$Name)
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Test-AnyPath {
    param([string[]]$Paths = @())
    foreach ($path in $Paths) {
        if (-not [string]::IsNullOrWhiteSpace($path) -and (Test-Path $path)) { return $true }
    }
    return $false
}

function Test-AgentInstalled {
    param(
        [string[]]$Commands = @(),
        [string[]]$EvidencePaths = @()
    )

    foreach ($command in $Commands) {
        if (Test-CommandExists $command) { return $true }
    }
    return Test-AnyPath $EvidencePaths
}

function Get-SharedRulesBody {
    $parts = @()
    foreach ($rule in $RuleDefinitions) {
        $path = Join-Path $RulesRoot $rule.Source
        if (-not (Test-Path $path -PathType Leaf)) { throw "Required shared rule not found: $path" }
        $content = [string](Get-Content $path -Raw -Encoding UTF8)
        if ([string]::IsNullOrWhiteSpace($content)) { throw "Shared rule is empty: $path" }
        $parts += $content.Trim()
    }
    return ($parts -join "`r`n`r`n")
}

function Get-ExpectedRulesAggregator {
    $body = Get-SharedRulesBody
    $header = @"
# Shared Agent Rules

> Generated from the canonical rule files in this directory. Edit the source rule files, then run ``setup.ps1``. Do not edit this file directly.
"@
    return ($header.Trim() + "`r`n`r`n" + $body.Trim() + "`r`n")
}

function Get-CursorRuleContent {
    param(
        [Parameter(Mandatory = $true)][string]$Description,
        [Parameter(Mandatory = $true)][string]$Content
    )

    return (@"
---
description: "$Description"
alwaysApply: true
---
$ManagedStart
$Content
$ManagedEnd
"@).Trim() + "`r`n"
}

function Set-TextFileIfChanged {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content,
        [Parameter(Mandatory = $true)][string]$Label
    )

    $parent = Split-Path $Path -Parent
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }

    $existing = ""
    if (Test-Path $Path -PathType Leaf) {
        $readContent = Get-Content $Path -Raw -Encoding UTF8
        if ($null -ne $readContent) { $existing = [string]$readContent }
    }

    if ((Normalize-Text $existing) -eq (Normalize-Text $Content)) {
        Write-Host "[OK]   $Label"
        return
    }

    [IO.File]::WriteAllText($Path, $Content, (New-Object Text.UTF8Encoding($false)))
    Write-Host "[UPDATE] $Label"
}

function Ensure-Junction {
    param(
        [Parameter(Mandatory = $true)][string]$Label,
        [Parameter(Mandatory = $true)][string]$SkillName,
        [Parameter(Mandatory = $true)][string]$JunctionPath,
        [Parameter(Mandatory = $true)][string]$TargetPath
    )

    $parent = Split-Path $JunctionPath -Parent
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }

    if (Test-Path $JunctionPath) {
        $item = Get-Item $JunctionPath -Force
        if ($item.LinkType -eq "Junction" -or $item.LinkType -eq "SymbolicLink") {
            foreach ($target in @($item.Target)) {
                if (Test-SamePath -PathA $target -PathB $TargetPath) {
                    Write-Host "[OK]   $Label already linked"
                    return
                }
            }
            Write-Warning "$Label has a different link at: $JunctionPath"
            return
        }

        if (-not (Test-Path $JunctionPath -PathType Container)) {
            Write-Warning "$Label has a real file at the skill path and was not changed: $JunctionPath"
            return
        }

        $destinationSkill = Join-Path $JunctionPath "SKILL.md"
        if (-not (Test-Path $destinationSkill -PathType Leaf)) {
            Write-Warning "$Label destination is not an AI skill directory and was not changed: $JunctionPath"
            return
        }

        $destinationText = [string](Get-Content $destinationSkill -Raw -Encoding UTF8)
        $escapedSkillName = [regex]::Escape($SkillName)
        if ($destinationText -notmatch ("(?m)^name:\s*" + $escapedSkillName + "\s*$")) {
            Write-Warning "$Label destination appears to belong to another skill and was not changed: $JunctionPath"
            return
        }

        Remove-Item $JunctionPath -Recurse -Force
        Write-Host "[MIGRATE] $Label replaced matching real skill directory with AI_MEMORY junction"
    }

    New-Item -ItemType Junction -Path $JunctionPath -Target $TargetPath | Out-Null
    Write-Host "[OK]   $Label linked: $JunctionPath"
}

function Remove-DirectoryLinkOnly {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) { return $true }
    $item = Get-Item $Path -Force
    if ($item.LinkType -ne "Junction" -and $item.LinkType -ne "SymbolicLink") { return $false }

    $comspec = if ([string]::IsNullOrWhiteSpace($env:ComSpec)) { "cmd.exe" } else { $env:ComSpec }
    $process = Start-Process -FilePath $comspec -ArgumentList @("/d", "/c", "rmdir `"$Path`"") -NoNewWindow -Wait -PassThru
    return ($process.ExitCode -eq 0 -and -not (Test-Path $Path))
}

function Remove-LegacyJunctionIfOwned {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$ExpectedTarget
    )

    if (-not (Test-Path $Path)) { return $true }
    $item = Get-Item $Path -Force
    if ($item.LinkType -ne "Junction" -and $item.LinkType -ne "SymbolicLink") { return $true }

    foreach ($target in @($item.Target)) {
        if (Test-SamePath -PathA $target -PathB $ExpectedTarget) {
            if (Remove-DirectoryLinkOnly -Path $Path) {
                Write-Host "[CLEAN] Removed legacy AI_MEMORY directory link: $Path"
                return $true
            }
            Write-Warning "Failed to remove legacy AI_MEMORY directory link: $Path"
            return $false
        }
    }

    Write-Warning "A different link already exists and was not changed: $Path"
    return $false
}

function Remove-ManagedFileIfOwned {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [string]$Label = "legacy managed file"
    )

    if (-not (Test-Path $Path -PathType Leaf)) { return }
    $content = [string](Get-Content $Path -Raw -Encoding UTF8)
    if ($content.Contains($ManagedStart) -and $content.Contains($ManagedEnd)) {
        Remove-Item $Path -Force
        Write-Host ("[CLEAN] Removed {0}: {1}" -f $Label, $Path)
    }
    else {
        Write-Warning "Refusing to remove unmanaged file: $Path"
    }
}

function Set-ManagedInstructionBlock {
    param(
        [Parameter(Mandatory = $true)][string]$AgentName,
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    $parent = Split-Path $Path -Parent
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }

    $block = "$ManagedStart`r`n$Content`r`n$ManagedEnd"
    $existing = ""
    if (Test-Path $Path) {
        $readContent = Get-Content $Path -Raw -Encoding UTF8
        if ($null -ne $readContent) { $existing = [string]$readContent }
    }

    $startIndex = $existing.IndexOf($ManagedStart)
    $endIndex = $existing.IndexOf($ManagedEnd)

    if ($startIndex -ge 0 -and $endIndex -gt $startIndex) {
        $endIndex += $ManagedEnd.Length
        $newContent = $existing.Substring(0, $startIndex) + $block + $existing.Substring($endIndex)
        Write-Host "[UPDATE] $AgentName global instruction"
    }
    elseif ($startIndex -ge 0 -or $endIndex -ge 0) {
        Write-Warning "$AgentName instruction has an incomplete AI_MEMORY marker. Skipped: $Path"
        return
    }
    elseif ([string]::IsNullOrWhiteSpace($existing)) {
        $newContent = $block + "`r`n"
        Write-Host "[SET]  $AgentName global instruction"
    }
    else {
        $newContent = $existing.TrimEnd() + "`r`n`r`n" + $block + "`r`n"
        Write-Host "[ADD]  $AgentName AI_MEMORY instruction block"
    }

    [IO.File]::WriteAllText($Path, $newContent, (New-Object Text.UTF8Encoding($false)))
}

function Sync-ManagedSkillCopy {
    param(
        [Parameter(Mandatory = $true)][string]$Label,
        [Parameter(Mandatory = $true)][string]$SkillName,
        [Parameter(Mandatory = $true)][string]$SourcePath,
        [Parameter(Mandatory = $true)][string]$DestinationPath
    )

    $parent = Split-Path $DestinationPath -Parent
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }

    if (Test-Path $DestinationPath) {
        $item = Get-Item $DestinationPath -Force
        if ($item.LinkType -eq "Junction" -or $item.LinkType -eq "SymbolicLink") {
            $owned = $false
            foreach ($target in @($item.Target)) {
                if (Test-SamePath -PathA $target -PathB $SourcePath) { $owned = $true; break }
            }
            if (-not $owned) {
                Write-Warning "$Label has a different link and was not changed: $DestinationPath"
                return
            }
            if (-not (Remove-DirectoryLinkOnly -Path $DestinationPath)) {
                Write-Warning "$Label legacy link could not be removed: $DestinationPath"
                return
            }
        }
        else {
            $destinationSkill = Join-Path $DestinationPath "SKILL.md"
            if (-not (Test-Path $destinationSkill -PathType Leaf)) {
                Write-Warning "$Label destination is not an AI skill directory and was not changed: $DestinationPath"
                return
            }
            $destinationText = [string](Get-Content $destinationSkill -Raw -Encoding UTF8)
            $escapedSkillName = [regex]::Escape($SkillName)
            if ($destinationText -notmatch ("(?m)^name:\s*" + $escapedSkillName + "\s*$")) {
                Write-Warning "$Label destination appears to belong to another skill and was not changed: $DestinationPath"
                return
            }
            Remove-Item $DestinationPath -Recurse -Force
        }
    }

    New-Item -ItemType Directory -Path $DestinationPath -Force | Out-Null
    Get-ChildItem -Path $SourcePath -Force | Copy-Item -Destination $DestinationPath -Recurse -Force
    Write-Host "[OK]   $Label copied as real files: $DestinationPath"
}

function Remove-ManagedSkillCopyIfOwned {
    param(
        [Parameter(Mandatory = $true)][string]$Label,
        [Parameter(Mandatory = $true)][string]$SkillName,
        [Parameter(Mandatory = $true)][string]$Path
    )

    if (-not (Test-Path $Path)) { return }
    $item = Get-Item $Path -Force
    if ($item.LinkType -eq "Junction" -or $item.LinkType -eq "SymbolicLink") {
        Write-Warning "$Label is a link and was not removed automatically: $Path"
        return
    }

    $skillFile = Join-Path $Path "SKILL.md"
    if (-not (Test-Path $skillFile -PathType Leaf)) { return }
    $text = [string](Get-Content $skillFile -Raw -Encoding UTF8)
    $escapedSkillName = [regex]::Escape($SkillName)
    if ($text -match ("(?m)^name:\s*" + $escapedSkillName + "\s*$")) {
        Remove-Item $Path -Recurse -Force
        Write-Host "[CLEAN] Removed stale AI_MEMORY skill copy: $Path"
    }
}

function Install-CursorLocalPlugin {
    param([Parameter(Mandatory = $true)][string]$CursorHome)

    $installRoot = Join-Path $CursorHome "plugins\local\ai-memory"
    if (-not (Remove-LegacyJunctionIfOwned -Path $installRoot -ExpectedTarget $CursorPluginRoot)) {
        Write-Warning "Cursor local plugin install skipped because the destination is a different link."
        return
    }

    if (-not (Test-Path $installRoot)) { New-Item -ItemType Directory -Path $installRoot -Force | Out-Null }
    $installItem = Get-Item $installRoot -Force
    if ($installItem.LinkType -eq "Junction" -or $installItem.LinkType -eq "SymbolicLink") {
        Write-Warning "Cursor local plugin destination is still a link and was not modified: $installRoot"
        return
    }

    Set-TextFileIfChanged -Path (Join-Path $installRoot ".cursor-plugin\plugin.json") -Content ([string](Get-Content $CursorPluginManifest -Raw -Encoding UTF8)) -Label "Cursor local plugin manifest"

    $installedRulesRoot = Join-Path $installRoot "rules"
    if (-not (Test-Path $installedRulesRoot)) { New-Item -ItemType Directory -Path $installedRulesRoot -Force | Out-Null }
    Remove-ManagedFileIfOwned -Path (Join-Path $installedRulesRoot "ai-memory.mdc") -Label "legacy combined Cursor rule"

    foreach ($rule in $RuleDefinitions) {
        $sourceAdapter = Join-Path $CursorPluginRulesRoot $rule.Adapter
        $targetAdapter = Join-Path $installedRulesRoot $rule.Adapter
        $adapterContent = [string](Get-Content $sourceAdapter -Raw -Encoding UTF8)
        Set-TextFileIfChanged -Path $targetAdapter -Content $adapterContent -Label "Cursor local plugin rule $($rule.Adapter)"
    }

    Write-Host "[OK]   Cursor local plugin copied as real files: $installRoot"
}

Write-Host ""
Write-Host "=== AI_MEMORY Setup ==="
Write-Host "Repository: $RepoRoot"
Write-Host ""

foreach ($required in @($SkillsRoot, $RulesRoot, $GlobalInstructionSource, $CursorPluginManifest)) {
    if (-not (Test-Path $required)) {
        Write-Error "Required item not found: $required"
        exit 1
    }
}

Write-Host "=== Shared Rules ==="
$rulesAggregator = Get-ExpectedRulesAggregator
Set-TextFileIfChanged -Path $RulesAggregatorPath -Content $rulesAggregator -Label "Shared rule aggregator: rules\RULES.md"

foreach ($rule in $RuleDefinitions) {
    $sourcePath = Join-Path $RulesRoot $rule.Source
    $sourceContent = [string](Get-Content $sourcePath -Raw -Encoding UTF8)
    $adapterContent = Get-CursorRuleContent -Description $rule.Description -Content $sourceContent.Trim()
    Set-TextFileIfChanged -Path (Join-Path $CursorPluginRulesRoot $rule.Adapter) -Content $adapterContent -Label "Cursor rule adapter: $($rule.Adapter)"
    Write-Host "[OK]   Rule source: rules\$($rule.Source)"
}

$globalInstruction = [string](Get-Content $GlobalInstructionSource -Raw -Encoding UTF8)
$managedInstruction = $globalInstruction.Trim() + "`r`n`r`n" + $rulesAggregator.Trim()

$currentHome = [Environment]::GetEnvironmentVariable("AI_MEMORY_HOME", "User")
if ([string]::IsNullOrWhiteSpace($currentHome) -or -not (Test-SamePath -PathA $currentHome -PathB $RepoRoot)) {
    [Environment]::SetEnvironmentVariable("AI_MEMORY_HOME", $RepoRoot, "User")
    Write-Host "[SET]  AI_MEMORY_HOME=$RepoRoot"
}
else { Write-Host "[OK]   AI_MEMORY_HOME=$currentHome" }
$env:AI_MEMORY_HOME = $RepoRoot

$codexHome = if (-not [string]::IsNullOrWhiteSpace($env:CODEX_HOME)) { $env:CODEX_HOME } else { Join-Path $HOME ".codex" }
$claudeHome = if (-not [string]::IsNullOrWhiteSpace($env:CLAUDE_CONFIG_DIR)) { $env:CLAUDE_CONFIG_DIR } else { Join-Path $HOME ".claude" }
$cursorHome = Join-Path $HOME ".cursor"
$geminiHome = Join-Path $HOME ".gemini"
$antigravityIdeSkillsHome = Join-Path $geminiHome "config\skills"
$antigravityCliSkillsHome = Join-Path $geminiHome "antigravity-cli\skills"
$staleAntigravityIdeSkillsHome = Join-Path $geminiHome "antigravity\skills"

$codexEvidence = @((Join-Path $codexHome "config.toml"))
$claudeEvidence = @((Join-Path $claudeHome "settings.json"))
$cursorEvidence = @()
$geminiEvidence = @((Join-Path $geminiHome "settings.json"))
$antigravityIdeEvidence = @((Join-Path $geminiHome "config"), (Join-Path $geminiHome "antigravity"))
$antigravityCliEvidence = @((Join-Path $geminiHome "antigravity-cli\settings.json"))

if (-not [string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
    $cursorEvidence += (Join-Path $env:LOCALAPPDATA "Programs\cursor\Cursor.exe")
    $antigravityIdeEvidence += (Join-Path $env:LOCALAPPDATA "Programs\Antigravity\Antigravity.exe")
    $antigravityCliEvidence += (Join-Path $env:LOCALAPPDATA "agy\bin\agy.exe")
}
if (-not [string]::IsNullOrWhiteSpace($env:ProgramFiles)) {
    $cursorEvidence += (Join-Path $env:ProgramFiles "Cursor\Cursor.exe")
    $antigravityIdeEvidence += (Join-Path $env:ProgramFiles "Antigravity\Antigravity.exe")
    $antigravityCliEvidence += (Join-Path $env:ProgramFiles "Google\antigravity-cli\agy.exe")
}

$codexInstalled = Test-AgentInstalled -Commands @("codex") -EvidencePaths $codexEvidence
$cursorInstalled = Test-AgentInstalled -Commands @("cursor", "agent") -EvidencePaths $cursorEvidence
$claudeInstalled = Test-AgentInstalled -Commands @("claude") -EvidencePaths $claudeEvidence
$geminiInstalled = Test-AgentInstalled -Commands @("gemini") -EvidencePaths $geminiEvidence
$antigravityIdeInstalled = Test-AgentInstalled -EvidencePaths $antigravityIdeEvidence
$antigravityCliInstalled = Test-AgentInstalled -Commands @("agy") -EvidencePaths $antigravityCliEvidence
$antigravityInstalled = $antigravityIdeInstalled -or $antigravityCliInstalled

Write-Host ""
Write-Host "=== Agent Detection ==="
$agentStatus = [ordered]@{
    "Codex" = $codexInstalled
    "Cursor" = $cursorInstalled
    "Claude Code" = $claudeInstalled
    "Gemini CLI" = $geminiInstalled
    "Antigravity IDE" = $antigravityIdeInstalled
    "Antigravity CLI" = $antigravityCliInstalled
}
foreach ($agent in $agentStatus.GetEnumerator()) {
    if ($agent.Value) { Write-Host "[OK]   $($agent.Key) detected" }
    else { Write-Host "[SKIP] $($agent.Key) not detected" }
}

$skillDirectories = @(
    Get-ChildItem -Path $SkillsRoot -Directory |
        Where-Object { Test-Path (Join-Path $_.FullName "SKILL.md") } |
        Sort-Object Name
)

Write-Host ""
Write-Host "=== Global Skills ==="
Write-Host "Detected skills: $($skillDirectories.Count)"
foreach ($skill in $skillDirectories) { Write-Host " - $($skill.Name)" }

$junctionSkillRoots = [ordered]@{}
if ($codexInstalled -or $cursorInstalled) { $junctionSkillRoots["Codex + Cursor"] = Join-Path $HOME ".agents\skills" }
if ($claudeInstalled) { $junctionSkillRoots["Claude Code"] = Join-Path $claudeHome "skills" }

$agentMemorySource = Join-Path $SkillsRoot "agent-memory"
if (Test-Path $agentMemorySource) {
    if ($codexInstalled) { Remove-LegacyJunctionIfOwned -Path (Join-Path $codexHome "skills\agent-memory") -ExpectedTarget $agentMemorySource | Out-Null }
    if ($cursorInstalled) { Remove-LegacyJunctionIfOwned -Path (Join-Path $cursorHome "skills\agent-memory") -ExpectedTarget $agentMemorySource | Out-Null }
}

if ($skillDirectories.Count -gt 0 -and $junctionSkillRoots.Count -gt 0) {
    Write-Host ""
    Write-Host "=== Skill Junctions ==="
    foreach ($skill in $skillDirectories) {
        foreach ($agent in $junctionSkillRoots.GetEnumerator()) {
            Ensure-Junction -Label "$($agent.Key) skill $($skill.Name)" -SkillName $skill.Name -JunctionPath (Join-Path $agent.Value $skill.Name) -TargetPath $skill.FullName
        }
    }
}
else { Write-Host "[SKIP] No skill junction work required." }

Write-Host ""
Write-Host "=== Gemini / Antigravity Skill Copies ==="
foreach ($skill in $skillDirectories) {
    if ($geminiInstalled) {
        Sync-ManagedSkillCopy -Label "Gemini CLI skill $($skill.Name)" -SkillName $skill.Name -SourcePath $skill.FullName -DestinationPath (Join-Path $geminiHome "skills\$($skill.Name)")
    }
    if ($antigravityIdeInstalled) {
        # Official Antigravity IDE global skills path.
        Sync-ManagedSkillCopy -Label "Antigravity IDE skill $($skill.Name)" -SkillName $skill.Name -SourcePath $skill.FullName -DestinationPath (Join-Path $antigravityIdeSkillsHome $skill.Name)
        # Cleanup a stale path used by an earlier AI_MEMORY setup revision.
        Remove-ManagedSkillCopyIfOwned -Label "stale Antigravity IDE skill $($skill.Name)" -SkillName $skill.Name -Path (Join-Path $staleAntigravityIdeSkillsHome $skill.Name)
    }
    if ($antigravityCliInstalled) {
        Sync-ManagedSkillCopy -Label "Antigravity CLI skill $($skill.Name)" -SkillName $skill.Name -SourcePath $skill.FullName -DestinationPath (Join-Path $antigravityCliSkillsHome $skill.Name)
    }
}

$legacyAntigravityAgents = Join-Path $geminiHome "config\AGENTS.md"
if (Test-Path $legacyAntigravityAgents -PathType Leaf) {
    $legacyContent = [string](Get-Content $legacyAntigravityAgents -Raw -Encoding UTF8)
    if ($legacyContent.Contains($ManagedStart) -and $legacyContent.Contains($ManagedEnd)) {
        Remove-ManagedFileIfOwned -Path $legacyAntigravityAgents -Label "legacy Antigravity managed AGENTS.md"
    }
    else {
        Write-Warning "Antigravity config AGENTS.md exists and may duplicate ~/.gemini/GEMINI.md. It was not modified: $legacyAntigravityAgents"
    }
}

Write-Host ""
Write-Host "=== Global Instructions + Shared Rules ==="
if ($codexInstalled) { Set-ManagedInstructionBlock -AgentName "Codex" -Path (Join-Path $codexHome "AGENTS.md") -Content $managedInstruction }
else { Write-Host "[SKIP] Codex global instruction" }

if ($cursorInstalled) {
    Remove-ManagedFileIfOwned -Path (Join-Path $cursorHome "rules\ai-memory.mdc") -Label "legacy Cursor home rule"
    Install-CursorLocalPlugin -CursorHome $cursorHome
}
else { Write-Host "[SKIP] Cursor global rule plugin" }

if ($claudeInstalled) { Set-ManagedInstructionBlock -AgentName "Claude Code" -Path (Join-Path $claudeHome "CLAUDE.md") -Content $managedInstruction }
else { Write-Host "[SKIP] Claude Code global instruction" }

if ($geminiInstalled -or $antigravityInstalled) {
    $geminiAgentName = if ($geminiInstalled -and $antigravityInstalled) { "Gemini CLI + Antigravity" } elseif ($geminiInstalled) { "Gemini CLI" } else { "Antigravity" }
    Set-ManagedInstructionBlock -AgentName $geminiAgentName -Path (Join-Path $geminiHome "GEMINI.md") -Content $managedInstruction
}
else { Write-Host "[SKIP] Gemini / Antigravity global instruction" }

Write-Host ""
Write-Host "=== Setup Complete ==="
Write-Host "AI_MEMORY_HOME: $RepoRoot"
Write-Host "Global skills: $($skillDirectories.Count)"
Write-Host "Shared rules: $($RuleDefinitions.Count)"
Write-Host "Cursor plugin rules: $($RuleDefinitions.Count)"
Write-Host "Restart running agents if they do not detect the changes immediately."
