param(
    [string]$Root = $env:AI_MEMORY_HOME
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

if (-not (Test-Path $Root)) { throw "AI memory root not found: $Root" }
$Root = (Resolve-Path $Root).Path

$memoryRoot = Join-Path $Root "memory"
$indexPath = Join-Path $Root "INDEX.md"
if (-not (Test-Path $memoryRoot)) { throw "Memory directory not found: $memoryRoot" }

function Get-MetaValue {
    param(
        [Parameter(Mandatory = $true)][string]$Text,
        [Parameter(Mandatory = $true)][string]$Key
    )

    $match = [regex]::Match($Text, "(?m)^$([regex]::Escape($Key)):\s*(.+)$")
    if ($match.Success) { return $match.Groups[1].Value.Trim().Trim('"').Trim("'") }
    return ""
}

function Get-RelativeRepositoryPath {
    param([Parameter(Mandatory = $true)][string]$FullPath)

    $rootPrefix = $Root.TrimEnd([char[]]"\/")
    $relative = $FullPath.Substring($rootPrefix.Length).TrimStart([char[]]"\/")
    return $relative.Replace("\", "/")
}

$rows = @()
Get-ChildItem -Path $memoryRoot -Recurse -File -Filter "*.md" | ForEach-Object {
    $text = Get-Content $_.FullName -Raw -Encoding UTF8
    $titleMatch = [regex]::Match($text, "(?m)^#\s+(.+)$")
    $title = if ($titleMatch.Success) { $titleMatch.Groups[1].Value.Trim() } else { $_.BaseName }

    $rows += [PSCustomObject]@{
        Type = Get-MetaValue $text "type"
        Status = Get-MetaValue $text "status"
        Project = Get-MetaValue $text "project"
        Id = Get-MetaValue $text "id"
        Title = $title
        Path = Get-RelativeRepositoryPath $_.FullName
    }
}

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("# Agent Memory Index")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("> Generated by scripts/rebuild-index.ps1. Prefer regeneration over manual edits.")
[void]$builder.AppendLine("")

foreach ($section in @("rule", "project", "lesson", "incident")) {
    $heading = switch ($section) {
        "rule" { "Rules" }
        "project" { "Projects" }
        "lesson" { "Lessons" }
        "incident" { "Incidents" }
    }

    [void]$builder.AppendLine("## $heading")
    [void]$builder.AppendLine("")

    $items = @($rows | Where-Object { $_.Type -eq $section -and $_.Status -ne "archived" } | Sort-Object Project, Title)
    if ($items.Count -eq 0) {
        [void]$builder.AppendLine("- None")
    }
    else {
        foreach ($item in $items) {
            $extra = if ($item.Project) { " | project: $($item.Project)" } else { "" }
            [void]$builder.AppendLine("- [$($item.Id)] $($item.Title) - `$($item.Path)`$extra")
        }
    }
    [void]$builder.AppendLine("")
}

[IO.File]::WriteAllText($indexPath, $builder.ToString(), (New-Object Text.UTF8Encoding($false)))
Write-Host "Rebuilt: $indexPath"
